apiVersion: v1
kind: Service
metadata:
  name: {{ include "smol-gang.gateway.fullname" . }}
  namespace: {{ include "smol-gang.namespace" . }}
  labels:
    {{- include "smol-gang.gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.gateway.port | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "smol-gang.gateway.selectorLabels" . | nindent 4 }}
