apiVersion: v1
kind: Service
metadata:
  name: {{ include "smol-cluster.gateway.fullname" . }}
  namespace: {{ include "smol-cluster.namespace" . }}
  labels:
    {{- include "smol-cluster.gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "smol-cluster.gateway.selectorLabels" . | nindent 4 }}
